#import "../EntryFragment.gql"

mutation(
  $projectId: ID!
  $description: String!
  $date: String
  $timerEstimatedTime: Int
) {
  entryCreateWithTask(
    projectId: $projectId
    description: $description
    date: $date
    timerEstimatedTime: $timerEstimatedTime
  ) {
    ...Entry
    date
    task {
      id
      description
      project {
        id
        color
        description
        category {
          id
          color
          description
        }
      }
      entries {
        id
      }
    }
  }
}
