#import "../EntryFragment.gql"

query($datesIn: [String!]!) {
  entries(filter: { date: { in: $datesIn } }) {
    ...Entry
    date
    task {
      id
      description
      project {
        id
        description
        category {
          id
          color
          colorContrast
          description
        }
      }
    }
  }
}
