#import "../EntryFragment.gql"

mutation(
  $taskId: ID!
  $date: String
  $timerEstimatedTime: Int
  $description: String
) {
  Entry: entryCreate(
    taskId: $taskId
    date: $date
    timerEstimatedTime: $timerEstimatedTime
    description: $description
  ) {
    ...Entry
    date
    task {
      id
      description
      project {
        id
        color
        description
        category {
          id
          color
          description
        }
      }
    }
  }
}
