#import "../EntryFragment.gql"

query {
  entries {
    ...Entry
    date
    task {
      id
      description
      project {
        id
        description
        category {
          id
          color
          colorContrast
          description
        }
      }
    }
  }
}
