mutation(
  $categorySelected: Number
  $dateZoomed: String
  $projectSelected: Project
) {
  settingsUpdate(
    categorySelected: $categorySelected
    dateZoomed: $dateZoomed
    projectSelected: $projectSelected
  ) @client {
    categorySelected @client
    dateZoomed @client
    projectSelected @client
  }
}
