query {
  categories {
    id
    description
    color
    colorContrast
    projects {
      id
      description
      targetDays
      targetMinTimePerWeek
      targetMaxTimePerWeek
      category {
        id
      }
    }
  }
}
