mutation($id: Int!, $description: String, $color: String) {
  Category: updateCategory(
    input: { patch: { color: $color, description: $description }, id: $id }
  ) {
    category {
      id
      description
      color
      colorContrast
    }
  }
}
