#import "../TaskFragment.gql"

mutation($projectId: ID!, $description: String!) {
  taskCreate(projectId: $projectId, description: $description) {
    ...Task
    project {
      id
    }
    entries {
      id
    }
  }
}
