#import "../TaskFragment.gql"

mutation($id: ID!, $projectId: ID, $description: String, $complete: Boolean) {
  taskUpdate(
    id: $id
    projectId: $projectId
    description: $description
    complete: $complete
  ) {
    ...Task
  }
}
