- hosts: webserver
  remote_user: root
  vars:
    NORMAL_USER_NAME: 'ansible'
  tasks:
    - name: "Create a secondary, non-root user"
      user: name={{ NORMAL_USER_NAME }}
            password='$6$rounds=656000$JL4dUmesOq41ysXW$d4iQim6Vbao3nCNadY1ra5D1YaQ2b9ALn.09fCLhDMHlI45e4uGUCzkOxH26DeJjHO6/ue6jMuzfjJhvuCAOe/'
            shell=/bin/bash
    - name: Add remote authorized key to allow future passwordless logins
      authorized_key: user={{ NORMAL_USER_NAME }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - name: Add normal user to sudoers
      lineinfile: dest=/etc/sudoers
                  regexp="{{ NORMAL_USER_NAME }} ALL"
                  line="{{ NORMAL_USER_NAME }} ALL=(ALL) ALL"
                  state=present
