query {
  targetsLastEntry: statsConnection(
    filter: {
      entryDate: { notEqualTo: "backlog" }
      entryComplete: { equalTo: true }
    }
  ) {
    groupedAggregates(
      groupBy: [
        CATEGORY_ID
        CATEGORY_DESCRIPTION
        PROJECT_ID
        PROJECT_DESCRIPTION
      ]
    ) {
      maxDate {
        entryDate
      }
      keys
    }
  }
}
