query ($datesIn: [String!]!) {
  targetsTime: statsConnection(filter: { entryDate: { in: $datesIn } }) {
    groupedAggregates(
      groupBy: [
        CATEGORY_ID
        CATEGORY_DESCRIPTION
        PROJECT_ID
        PROJECT_DESCRIPTION
      ]
    ) {
      sum {
        entryTimerEstimatedTime
        entryTimerTrackedTime
      }
      keys
    }
  }
}
