mutation($id: ID!, $categoryId: ID, $description: String, $color: String) {
  projectUpdate(
    categoryId: $categoryId
    id: $id
    description: $description
    color: $color
  ) {
    id
    description
    color
  }
}
