mutation($id: Int!, $description: String!, $targetDays: Int) {
  Project: updateProject(
    input: {
      patch: { description: $description, targetDays: $targetDays }
      id: $id
    }
  ) {
    project {
      id
      description
      targetDays
    }
  }
}
