#import "../EntryFragment.gql"

mutation(
  $taskId: Int!
  $date: String
  $timerEstimatedTime: Int
  $description: String
) {
  Entry: createEntry(
    input: {
      taskId: $taskId
      date: $date
      timerEstimatedTime: $timerEstimatedTime
      description: $description
    }
  ) {
    entry {
      ...Entry
      task {
        id
        description
        project {
          id
          description
          category {
            id
            color
            colorContrast
            description
          }
        }
      }
    }
  }
}
