[tool.poetry]
name = "reflex-apps"
version = "0.1.0"
description = ""
authors = ["oliveryh"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
reflex = "^0.5.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
